### PR TITLE
Upgrade guzzle version to 7.4.5

### PR DESCRIPTION
**Pull request by nicocucuzza**

### CODE REVIEW

**Comment by nicocucuzza** [comment]
[(2) sso-awardforce-wordpress dependabot alert [2]](https://trello.com/c/D1T0dDyI/5191-2-sso-awardforce-wordpress-dependabot-alert-2)

**Review by kirkbushell — APPROVED** [review]
At first I was wondering why there were so many changed files - then I realised it's the wp plugin lol

**Comment by eyalgrossdev** [comment]
Is this good to go @nicocucuzza ?

**Comment by nicocucuzza** [comment]
It's on QA

**Pull request merged**
